### ISSUE TITLE
Deploy every commit to release branches to staging

### ISSUE THREAD

**Issue by cmiacz** [saleor/saleor-dashboard#3494]
Add on-push-branches trigger to deloy-staging workflow
```
on:
  push:
    branches:
      # Matches release branches
      - "[0-9]+.[0-9]+."
```

- In case of branch push trigger we should override APP_VERSION with proper commit hash
- Opening release PR should be triggered only for tagged releases
