### ISSUE TITLE
[Bug]: fetch-schema doesn't work

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-dashboard#3752]
### Description of the issue

`fetch-schema` script uses following graphql-codegen config

```
schema: ${API_URI}
generates:
  ./introspection.json:
    plugins:
      - introspection
  ./schema.graphql:
    plugins:
      - schema-ast

```

However the script itself does not pass `API_URL` from `.env` to the environment.

When `${API_URL}` replaced with graphql URL, it works

### Steps to reproduce the problem

Run `npm run fetch-schema`

### What did you expect to happen?

1. If `.env` exist, script will load API_URL and use it in codegen
2. If `.env` doesn't exist, script will give me an error that I need to set it first

### Additional information

I suggest to have a simple node script that will `require('dotenv')` and run graphql-codegen programmatically (or throw with exhaustive message)

### Environment

Browser and version: …
OS and version: …
Dashboard version: …
Core version: …
