### ISSUE TITLE
[Bug] regression: .env API_URL no longer works in 3.20

### ISSUE THREAD

**Issue by djkato** [saleor/saleor-dashboard#5198]
### Description of the issue

when building with the following .env it worked in 3.19.x:
```toml
API_URI="https://api.site.com/graphql/"
APP_MOUNT_URI="/"
APPS_MARKETPLACE_API_URI="https://apps.saleor.io/api/v2/saleor-apps"
STATIC_URL="https://admin.site.com/"
```
and when going to `https://admin.site.com/` it would let me log in, and do API calls to corrent API_URL

In 3.20 or main branch, the dashboard attempted to do all api calls to `https://admin.site.com/graphql/`, which obviously lead to 405 and broken admin

### Steps to reproduce the problem

clone master branch, use env mentioned above, try to access admin panel through caddy or smt.

### What did you expect to happen?

The correct API endpoint to be hit

### Environment

Browser and version:firefox latest
OS and version: docker
Dashboard version: 3.20 (master)
Core version: 3.20.34
